leouieda/website

- .travis.yml
Weren't used anymore so I'll remove them from the travis build setup
> Remove ipython, pillow and nodejs as dependencies

- conf.py
- theme/templates/base.html
Simplify template with right, middle, left footer config variables. Add
the build date and commit hash of the latest build. Say CC-BY instead of
full name.
> Tweaks to footer

- about/bachelors.md
- about/index.md
- about/masters.md
- about/phd.md
- papers/paper-planting-anomalous-densities-2012.md
Put more info and links on each page
> Separate education into pages

- about/index.md
Put the 4 entries in my education list on a single row.
Instead of putting the york u exchange under bsc.
Looks nicer and collapses to a single column on mobile.
> Single row for 4 education entries

- _layouts/page.html
- css/style.css
- index.md
Adds a banner_position entry that sets the background-position css
attribute. Default's to center.
> Metadata entry to control banner position

- papers/paper-moho-inversion-tesseroids-2016.md
The paper is been published in the journal and has a doi. Update the PDF
to the unformatted version from the GJI website.
> Adds DOI + update PDF of Moho paper

- _layouts/blog.html
- _layouts/home.html
- _layouts/index.html
- _layouts/post.html
- _layouts/publication.html
- _layouts/rss.html
- _layouts/utils.html
- _site.yml
- blog/.sample-post.md
- blog/index.md
- css/style.css
- rss.md
Implements placeholders and all templates needed for blog.
It won't be included in the nav or front page until there is a post.
> Required basis for a blog

- _layouts/rss.html
- _site.yml
Modifications to the RSS layout to make it validate in
https://validator.w3.org/feed/
> Validate the RSS feed format

- _layouts/rss.html
- _site.yml
The rss .url field is html not xml. So I can't build it in the template.
> Revert back to getting the rss url from _site.yml

- papers/paper-moho-inversion-tesseroids-2016.md
Include the volume and issue numbers as well.
> Update citation for moho paper to 2017

- _layouts/about.html
- _layouts/utils.html
- about/bachelors.md
- about/index.md
- about/masters.md
- about/phd.md
Generate the education section in the layout, not by hand. Add some
entries to the education info sidebars. Simplify social media links.
> New layout for about page

- _layouts/home.html
- css/style.css
It allows more cards for each category and is less cluttered.
> Use a single column in the homepage

- .travis.yml
And turn off email notifications
> Only build pushes to the master branch

- blog/scipy-on-android.md
Fixes #69 
Ran everything to make sure all worked this time.
Broke down the install instructions for each package.
Add tip about enabling extra keys on touch keyboard.
>  Update Termux instructions with all requirements

- papers/nmo-tutorial.md
Also mention that pdf is free by following doi
link
> Remove "Geophysical tutorial" from title

- _layouts/base.html
- _site.yml
Try to fix the broken Google analytics code. Embed it into base template
and remove config option from _site.yml
> Update GA tracking code

- css/style.css
Follow the example from
http://getbootstrap.com/examples/sticky-footer-navbar/
> Make footer stick to bottom of page

- contact/index.md
Make it two column and add h2 headers
> Add UH address to contacts page

- .travis.yml
This will decrease the build time, hopefully.
> Cache miniconda download and pip pkgs in Travis

- _layouts/utils.html
Insert it into the feedback utility macro
> Add the disqus code to render comments on pages

- _layouts/nav.html
- _site.yml
- about/index.md
- contact/index.md
- css/style.css
Separated the nav icons into a col of their own. This way they collapse
below the section names always. Added google+ and linkedin links to the
nav. Added some more space between elements.
> Separate nav icons, add more social, more space

- _layouts/utils.html
- css/style.css
Make them a bit lighter color and remove the top and bottom padding.
Also fix dates with different colors (now they all have the same) and
add a bit of space after the feedback box
> Add some styling for block quotes

- _layouts/utils.html
- css/style.css
Ask people to contribute spelling fixes etc though github on the
feedback box.
> Add "edit on github" link to feedback

- _layouts/post.html
It loops better and doesn't interfere with the post so much
> Use a smaller sidebar in blogposts

- _layouts/post.html
- blog/scipy2017-proposal-gmt.md
Show 2 latest always in side bar
> Change date on scipy post to make sure it's last

- blog/python-hawaii-2017.md
There title tag in HTML doesn't like them.
> Removes quotes from title

- _site.yml
- rss.md
The other parts aren't fit for something like planet feeds.
> Only include blog posts in RSS feed

- software/fatiando.md
Add TGIF talk at UH and embed the youtube video os Scipy.
> Update list of presentations about Fatiando

- about/index.md
Fix the icon spacing in the links list.
> Add a short bio to About and separate CV section

- _layouts/base.html
- css/style.css
The bold text wasn't showing properly on mobile. Maybe this will help.
> Add bold Open Sans from google fonts

- _layouts/home.html
- _layouts/rss.html
- _site.yml
Need to strip the html tags when using it in RSS and social media cards
> Add a line break to the description

- about/index.md
> Remove "passionate" from about page

- _site.yml
- contact/index.md
I don't even login anymore. Time for an update.
> Update contact info, remove Google+

- _layouts/teaching.html
- _layouts/utils.html
The two column layout is a bit strange. Make it a single column of
cards.
> Make teaching page a single column

- _layouts/home.html
- _layouts/utils.html
- css/style.css
Don't need the custom recent_cards macro. Added an option to make_index
to limit the number of cards.
> Use make_index macro in the home page layout

- _layouts/tag.html
- _layouts/utils.html
- css/style.css
- papers/paper-tesseroids-2016.md
- posters/goce2011.md
- posters/simposio-iag-2008.md
- research/index.md
- talks/agu2010.md
- talks/scipy2018.md
Made some style changes to the research page to add more spacing and
added the "forward-modeling" tag.
> More spacing in Research page and better tags

- _layouts/base.html
- _layouts/home.html
- _layouts/utils.html
- css/style.css
- index.md
It looks a lot nicer. Introduce a gradient to the banner to darken the
top for more contrast with the menu.
Add some space between the indexes on the front page as well.
> Use a transparent menu on pages with banners

- blog/job-sites.md
Thanks to Stefanie Donner for contributing.
> Add academics.de to job sites list

- blog/job-sites.md
Japanese jobs. Contributed by Hakim Saibi.
> Update job sites post with JREC-IN

- about/index.md
- blog/gmt-after-scipy2017.md
- blog/gmt-at-agu2017.md
- blog/gmt-python-design.md
- blog/hawaii-gmt-postdoc.md
- blog/scipy2017-proposal-gmt.md
- blog/scipy2017-reviews.md
- posters/agu2017.md
- posters/aogs2018.md
- research/index.md
- talks/scipy2017.md
- talks/scipy2018.md
Update the package name and website in Research. Keep the others to have
a record. Rename the tag to pygmt.
> Replace GMT/Python with PyGMT

- _layouts/utils.html
- css/style.css
- papers/paper-moho-inversion-tesseroids-2016.md
Reworked the templating for the ALM badge display and added a
dimensions.ai badge for citations.
> Add preprint metadata entry and citation badges

- _layouts/base.html
Gives visitors a lot more privacy
> Disable Google Analytics cookies and anonymize IPs

- papers/tesseroid-variable-density.md
> Add DOIs to tesseroids variable density paper

- _templates/macros.html
Minor thing spotted while stealing your macros ;-)
> Remove duplication in figure macro

- cv/supervision-phd.yml
Update title of Santi's PhD Thesis.
> Fix Santi's thesis title
