_site.yml

Shouldn't copy conda env, ci-tools,and miniconda install script to the
_build  folder. They will get deployed to the website

Don't deploy some files

---

_layouts/home.html
_layouts/page.html
_layouts/publication.html
_site.yml
index.md

Make the banner image in the homepage optional for every page to define
in its metadata. Might be useful for blogposts or other pages. Had to
move things from index.md to the page.html template and switch around
some other parts of the template.

Add banner metadata arg for pages

---

css/style.css

It doesn't make much of a difference on desktop but in smaller screens
it looks more in place with the rest of the page

No left-right padding for the site description

---

.travis.yml
_layouts/base.html
_layouts/home.html
_layouts/nav.html
_layouts/page.html
_layouts/publication.html
_layouts/utils.html
_site.yml
index.md

Moves a portion of the template constructs to macros so that they can be accessed from other templates (particularly the side bar for publications). This will pave the way for the RSS feeds (#36).

Refactor the template to reuse components

---

_layouts/base.html

The `author` HTML metadata was using just `site.author` when it should
be `site.authors[site.author]` after the recent template refactoring.

Get full name from authors dict in author metadata

---

_layouts/utils.html
about/index.md
papers/index.md
talks/index.md

Swapped around some icons because the square github icon doesn't really
work in small sizes. Using the </> icon now and changed some others to
accommodate. Removed mentions of the icon from the text.

Add comments icon and replace github repo icon

---

_layouts/utils.html
_site.yml
contact/index.md

The old swung.rocks seems to be broken. Update to the new
softwareunderground.org and move all references to a reflink in
_site.yml to make it easier to update in the future.

Update links to swung and centralize in _site.yml

---

_layouts/about.html
_layouts/post.html
_layouts/publication.html
_layouts/utils.html
about/index.md
contact/index.md
css/style.css
papers/paper-moho-inversion-tesseroids-2016.md

* Reuse the card macro on the blog roll by adding an option to collapse
the post title to the side of the thumbnail
* Put education list below the content of about. Makes the look of the
page more natural
* Full width thumbnail in blog posts
* Citation below publication body instead of info bar
* Larger text and line-height (had to tweak line height for font-awesome
icons a bit)
* Less left padding in info bar icons in publication
* Contact in single column with each map to the right
* Add google plus to contact

A few tweaks to style and template

---

_layouts/utils.html
talks/agu-cancun2013.md
talks/agu2010.md
talks/egu2014.md
talks/gghs2012.md
talks/iag-04-2015.md
talks/sbgf2011.md
talks/scipy2013.md
talks/seg-carlos2012.md
talks/seg2011.md
talks/seg2012.md
talks/tgif-2017.md

If an HTML link (using "<a" and "</a>") is given in "slides", "poster",
or "repository", will insert that in the info bar. Allows inserting HTML
slides that aren't on figshare.

Allow html in "slides" and "poster" header tags

---

_layouts/utils.html

Insert documentation comments in macro definitions.
Use https://doi.org instead of http://dx.doi.org for doi links.

Use a macro to convert slides and poster to a link

---

.travis.yml

Github revoked the old token after a security breach at Travis. Update
it with a new one just to be sure.

Update TravisCI access token

---

_layouts/about.html
_layouts/base.html
_layouts/page.html
_layouts/utils.html
about/bachelors.md
about/masters.md
about/phd.md

It got a bit confusing. Use the degree name instead. Set thesis title as
metadata and insert in info sidebar. This allows using the title and
thesis title in the about page as well. Strip formatting from titles
when setting the "title" in the header.
Add sucupira entry for PhD thesis.

Remove thesis title from page titles

---

about/index.md

Point to autogenerated file on *pdf* branch instead of Github release
page.

Update the link to the latest CV PDF

---

_layouts/base.html

The W3C validator (https://validator.w3.org/) pointed out these issues

Fix some issues with the HTML syntax

---

posters/aogs2018.md
talks/aogs2018.md

Some context to what the work is related. Renamed the talk page to 2018
(it was 2017). Good thing I haven't shared a link yet.

Add more information about AOGS presentations

---

about/bachelors.md
papers/nmo-tutorial.md
papers/paper-mag-dir-2015.md
papers/paper-moho-inversion-tesseroids-2016.md
papers/paper-planting-anomalous-densities-2012.md
papers/paper-tle-euler-tutorial-2014.md
posters/goce2011.md
software/tesseroids.md

Hello :-)
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Yes, a bit ironic, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org) and the old links with the `dx` subdomain continue to work.
So, there is no urgent need to do anything, but nonetheless, I'd like to suggest to hereby update all static DOIs.
Cheers!

Hyperlink DOIs against preferred resolver

---

_layouts/base.html
_layouts/blog.html
_layouts/home.html
_layouts/index.html
_layouts/page.html
_layouts/post.html
_layouts/publication.html
_layouts/teaching.html
_layouts/utils.html
css/style.css

Remove the side columns from publications and blog posts. Instead, put
them at the bottom of the page to avoid distractions. Use a media query
to make the content column narrower or lager screens for better
readability. Use multiple columns for ALM badges.

Single column layout with narrower text

---

_layouts/index.html
_layouts/tag.html

They inherited from index.html and defined the content block, which
didn't exist anymore. Add it back to index but tag.html inherits from
page.html now.

Fix broken template for tag pages

---

papers/paper-moho-inversion-tesseroids-2016.md

It no longer works and I have no intention of updating this right now.
Fixed the link to Fatiando as well.

Remove Binder link from Moho inversion paper

---

research/index.md

In the research page, show cards for specific software as well as the
overall "open-source" tag

Add specific cards for each software project

---

css/style.css

Was setting it wrong in the css so the badge was deformed on some
screens

Correctly set altmetric badge width to auto
